config/routes.rb
Rails.application.routes.draw do
    root 'users#index'
    post '/users' => 'users#create'
    get '/items' => 'items#index'
    get '/purchases' => 'purchases#index'
    post '/items' => 'items#create'
    post '/sessions' => 'items#index'
    get '/sessions' => 'items#index'
    delete '/sessions' => 'sessions#destroy'
    get '/users' => 'users#index'
    get '/purchases/add' => 'purchases#index'
    get '/destroy' => 'items#destroy'
end

app/models/item.rb
class Item < ActiveRecord::Base

    belongs_to :sales
    belongs_to :purchases

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  belongs_to :sales
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  belongs_to :purchases
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :sales
  has_many :purchases
  belongs_to :item

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :first_name, :last_name, presence: true, length: { in: 2..20 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }  

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    def index
        @items = Item.all
        User.all
    end

    def create
        @item = Item.new(user_params)
        if @item.save
            redirect_to "/items", notice: "Item was successfully created."
        else
            flash[:errors_register] = @item.errors.full_messages
            redirect_to :back
        end
    end
  
    private
        def user_params
            params.require(:item).permit(:product, :amount)
        end

    def destroy
        redirect_to :back
    end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

    def index
        @unsold = Item.all
        @sales = Sale.all
        @purchases = Purchase.all
    end

    # def create
    #     @add = Purchase.new(:product=item.product, :amount=item.amount)
    #     if @add.save
    #         redirect_to "/purchases", notice: "Item was successfully added to purchases."
    #     else
    #         flash[:errors_register] = @add.errors.full_messages
    #         redirect_to :back
    #     end
    # end
  
    # private
    #     def purchase_params
    #         params.require(:item).permit(:product, :amount)
    #     end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
  
    end

    # def profile
    #     user = User.all
    #     @users = User.all
    #  end
  
    def create
        # user = User.find_by(email: params[:user][:email]).try(:authenticate, params[:user][:password])
        # if email address is blank
        if params[:session][:email].blank?
            flash[:errors_login] = "Email must not be blank"
            redirect_to :back
        # if email address does not exist in database
        elsif User.find_by(email: params[:session][:email]).nil?
            flash[:errors_login] = "A user with this email address does not exist in the database"
          redirect_to :back
        # if email address exists in the database but password does not match
        elsif !(User.find_by(email: params[:session][:email]).try(:authenticate, params[:session][:password]))
            # redirect_to new_user_path, :flash => { :error => 'Email and password don\'t match.' }
            flash[:errors_login] = "Email and password do not match"
            redirect_to :back
        # otherwise, email address and password match -> success!
        else
        user = User.find_by(email: params[:session][:email]).try(:authenticate, params[:session][:password])
            sign_in user
            redirect_to users_path
        end
    end
  
    def destroy
      sign_out
      redirect_to users_path
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
    end

    def new
        @user = User.new
    end
  
    def create
        @user = User.new(user_params)
        if @user.save
        sign_in @user
            redirect_to "/items", notice: "User was successfully created."
        else
            flash[:errors_register] = @user.errors.full_messages
            redirect_to :back
        end
    end
  
    def show
      @user = User.find(params[:id])
    end
  
    def edit
    end
  
    private
        def user_params
            params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
        end

 
     def destroy
     end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def sign_in(user)
      session[:user_id] = user.id
      self.current_user = user
    end
    
    # setter method
    def current_user=(user)
      @current_user = user
    end
  
    # getter method
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  
    def signed_in?
      !current_user.nil?
    end
  
    def sign_out
      session[:user_id] = nil
      self.current_user = nil
    end
  
    def current_user?(user)
      user == current_user 
    end
  
    def deny_access
      redirect_to welcome_path, :notice => "Please sign in to access this page."
    end
  
  end

app/views/items/index.html.erb
<div class="container">
		<% if flash[:errors_register] %>
			<p>Please correct the following errors:</p>
			<% flash[:errors_register].each do |error| %>
				<p class='error'><%= error %></p>
			<% end %>
		<% end %>

<%= link_to 'Go to Dashboard', purchases_path %>
<%= link_to 'Logout', sessions_path(current_user), method: :delete, class: 'btn btn-primary'%>

<h1>Hello <%= @first_name %> ! </h1>

<h3>All Products</h3>
<div class="products">
	<table>
		<thead>
			<tr>
				<th>Product</th>
				<th>Seller</th>
                <th>Date Posted</th>
				<th>Amount</th>
                <th>Action</th>
			</tr>
		</thead>
		<tbody>
			<% @items.each do |i| %>
				<tr>
					<td><%= i.product %></td>
					<td><%= i.seller %></td>
					<td><%= i.date_posted %></td>
                    <td><%= i.amount %></td>
					<td>
						<a href="/purchases/add">Buy</a>
					</td>
				</tr>
			<% end %>	
		</tbody>
	</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoesale</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/purchases/index.html.erb
<div class="container">
		<% if flash[:errors_register] %>
			<p>Please correct the following errors:</p>
			<% flash[:errors_register].each do |error| %>
				<p class='error'><%= error %></p>
			<% end %>
		<% end %>

<%= link_to 'Go to All Products', items_path %>
<%= link_to 'Logout', sessions_path(current_user), method: :delete, class: 'btn btn-primary'%>

<div class="sell_product">
    <h3>Sell Product</h3>
    <form action="/items" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="text" name="item[product]" value="Name">
        <input type="text" name="item[amount]" value="Amount">
        <input type="submit" value="Sell">

</div>

<h3>Your products that that are not yet sold:</h3>
<div class="unsold">
	<table>
		<thead>
			<tr>
				<th>Product</th>
                <th>Date Posted</th>
				<th>Amount</th>
                <th>Action</th>
			</tr>
		</thead>
		<tbody>
			<% @unsold.each do |u| %>
				<tr>
					<td><%= u.product %></td>
					<td><%= u.date_posted %></td>
                    <td><%= u.amount %></td>
					<td>
						<a href="/destroy">Remove</a>
					</td>
				</tr>
			<% end %>	
		</tbody>
	</table>
</div>

<h3>Sales</h3>
<div class="sales">
	<table>
		<thead>
			<tr>
				<th>Product</th>
                <th>Date Bought</th>
                <th>Buyer</th>
				<th>Amount</th>
			</tr>
		</thead>
		<tbody>
			<% @sales.each do |s| %>
				<tr>
					<td><%= s.product %></td>
					<td><%= s.date_posted %></td>
                    <td><%= s.seller %></td>
                    <td><%= s.amount %></td>
				</tr>
			<% end %>	
		</tbody>
	</table>
</div>

<h3>Purchases</h3>
<div class="purchases">
	<table>
		<thead>
			<tr>
				<th>Product</th>
                <th>Date Bought</th>
                <th>Seller</th>
				<th>Amount</th>
			</tr>
		</thead>
		<tbody>
			<% @purchases.each do |p| %>
				<tr>
					<%# <td><%= p.product %></td> 
					<td><%= p.date_bought %></td>
                    <%# <td><%= p.seller %></td> 
                    <%# <td><%= p.amount %></td> 
				</tr>
			<% end %>	
		</tbody>
	</table>
</div>

app/views/users/index.html.erb
<div class="container">
	<h1>Register</h1>
		<% if flash[:errors_register] %>
			<p>Please correct the following errors:</p>
			<% flash[:errors_register].each do |error| %>
				<p class='error'><%= error %></p>
			<% end %>
		<% end %>

<div class="Registration">
    <form action="/users" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="text" name="user[first_name]" placeholder="first_name"/>
        <input type="text" name="user[last_name]" placeholder="last_name"/>
        <input type="text" name="user[email]" placeholder="email"/>
        <input type="text" name="user[password]" placeholder="password"/>
        <input type="text" name="user[password_confirmation]" placeholder="password_confirmation"/>
        <input type="submit" value="Register"/>
    </form>
</div>

<h2>Login</h2>
<div class="Login">
    <form action="/sessions" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <p>
            <label>Email</label>
            <input type="text" name="email">
        </p>
        <p>
            <label>Password</label>
            <input type="password" name="password">
        </p>
        <input type="submit" value="Login">
    </form>
</div>